# Site Settings
title: "Mohammed Brueckner, passionate Leader, Advisor and IT Architect"
description: "Results-oriented tech leader driving innovation and transformative growth through strategic alignment of business objectives with cutting-edge cloud (Azure/AWS), AI/IoT/Data solutions. Specializes in practical AI (GenAI/MLOps) implementation for Azure-driven strategic advantage. Empowers high-performing teams, communicates complex concepts effectively, and adapts quickly to dynamic environments to deliver exceptional outcomes."
url: "https://mobruec.github.io/MoBRUEC/"
baseurl: "/MoBRUEC" # Often useful if your site isn't at the root of the domain. If it is, you can leave this blank or remove it.
author: "Mohammed Brueckner"

# Jekyll Theme
theme: jekyll-theme-architect

# Keywords for SEO and Crawlers (Extracted from your additional content)
keywords: >- # Using the >- allows for a multi-line string that gets read as a single line with spaces, which is often good for keyword meta tags.
  Mohammed Brueckner, Leader, Advisor, IT Architect, Tech Leader, Innovation,
  Cloud, Azure, AWS, AI, Artificial Intelligence, IoT, Internet of Things, Data,
  GenAI, Generative AI, MLOps, Strategic Advantage, High-performing teams,
  IT Consulting, Architecture, Information Security, Custom Software Development,
  Program Management, Change Management, Management Consulting, Research Skills,
  Cloud Management, Public Speaking, Tech Visionary, Microsoft, Bosch, adidas,
  Automation, Team Leadership, Retail, Finance, Insurance, Strategic Planning,
  Enterprise Architecture, Design Thinking, Cloud Computing, CRM, Sales,
  Software Solution Architect, German, English

# Social Links
social_links:
  - name: LinkedIn
    url: "https://www.linkedin.com/in/mbrueckner/"
    icon: "fab fa-linkedin" # Ensure your theme or custom CSS supports Font Awesome icons
  - name: Spotify
    url: "https://open.spotify.com/show/0LUvemwzThUrQR8f5UmFRW?si=-X6NRDacSeCOvHizduAUzw" # Note: This Spotify URL seems unusual. You might want to double-check it.
    icon: "fab fa-spotify"
  - name: Medium
    url: "https://medium.com/@mohammedbrueckner"
    icon: "fab fa-medium"

# --- Optional but Recommended Additions ---

# GitHub Metadata (if using jekyll-github-metadata plugin - common on GitHub Pages)
# repository: MoBRUEC/MoBRUEC # Automatically inferred on GitHub Pages, but good to be explicit.

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enables GitHub Flavored Markdown

# Plugins (GitHub Pages often restricts plugins, but these are common)
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag # HIGHLY recommended for SEO and LLM discoverability

# --- End of _config.yml ---
